### ISSUE TITLE
ftc_http updates not being pushed on Robot Controller v7.0

### ISSUE THREAD

**Issue by mdyks01** [TheLostLambda/ftc_http#10] opened 2021-09-27 15:33 UTC
First, thanks for this tool.  We have been using it heavily this past offseason.

Issue: After updating to the latest libraries released for Freight Frenzy, pushing updated source files doesn't seem to be working.  I can push a new file without a problem.  But if I try to push an update to an existing source file, it just quietly fails.  The push says "done" like it worked.  But checking the source file, it's still the old, original file.

Environment:

Robot Controller version:7.0
Control Hub OS version:1.1.1
REV Hub firmware versions:
Control Hub: 1.8.2
Expansion Hub 2: 1.8.2

If I new Rust, I'd look into it but I'm afraid I don't.

Thanks
Marc

**Comment by TheLostLambda** [comment] 2021-09-28 08:28
Hi @mdyks01 ! Thanks for opening an issue and using this tool!

Just to double-check, have you confirmed that using updating an existing file via the OnBotJava web interface still works? I suspect that they may have changed part of the API, but it would be good to rule out a bug on their side as well.

Additionally, have you played with Wireshark before and do you think you could send a packet capture of updating a file via the web interface? If not, that's totally fine, but I might need a week or so to get around to this :)

If it's been any longer than a week though, feel free to pester me some more! I know the season is probably already underway!

**Comment by mdyks01** [comment] 2021-09-28 19:10
Thanks for the quick response.  I am familiar with wireshark so I might be able to get you that trace, but now that you suggested I try the OnBotJava upload feature, the problem seems pretty clear.  They are now putting up an error if the file you are uploading already exists.  See attached screenshot.  I tried to upload a modified "test.java" when "test.java" already existed.

I don't see a setting to override this.  If "ftc_http --upload" was able to do a delete first, then it would work again.  The -w options seems to only wipe everything so that would work but you'd have to wipe then upload everything every time.

![ftc_http_upload_error](https://user-images.githubusercontent.com/60412258/135149776-da02fb43-1c1a-4308-b3b0-1391d88051d5.png)
t.

**Comment by TheLostLambda** [comment] 2021-09-28 21:43
@mdyks01 Thanks for the quick investigative work! I think that you're right about deleting files before uploading them being the best approach here overall :)

I'll do some looking into how this error can be detected (I assume a different response if returned when the error occurs), or how deleting potentially non-existent files goes.

I should have this fixed in the next week or so – especially with all of the helpful information you've provided so far!

**Comment by TheLostLambda** [comment] 2021-10-09 19:25
Hey @mdyks01 ! 

This should be fixed now on master! Hopefully I can do a release soon, I just need to fix my broken cross-compilation setup :sweat_smile: 

Feel free to test things if you want to build the program from source, otherwise hang with me for another day :)

**Comment by TheLostLambda** [comment] 2021-10-10 20:17
@mdyks01 Just created a new release that should solve this issue! Please let me know if you get the chance to test it out!

**Comment by mdyks01** [comment] 2021-10-13 15:57
Thanks for the release build. I was able to test it just now and I'm not seeing any difference.  If the file already exists in OnBotJava, the upload quietly fails.  I verified I'm running v2.1.0.  ftc_http -h produces "ftc_http 2.1.0".  Doing ftc_http --upload file.java produces:

Trying host http://192.168.43.1:8080...online
Pushing file.java...done

But after reloading OnBotJava, 'file.java' hasn't changed (if it already existed).

I'm running v7.0 of the Robot Controller.

Let me know if you need me to try anything.  Thanks.

**Comment by TheLostLambda** [comment] 2021-10-14 22:48
Sorry @mdyks01 ! It looks like some things broke at the last minute there! You are totally right! I'm working on another patch to fix things now. Sorry for all for all of the trouble!

**Comment by TheLostLambda** [comment] 2021-10-15 02:28
Hey @mdyks01 ! I'm pretty sure things are fixed in the latest commit!

Could you try some of these binaries here: https://github.com/TheLostLambda/ftc_http/actions/runs/1344324496 ?

If those work for you, I'll wrap up a couple of loose ends and release again!

You may need to run `ftc_http --restore-defaults` if you have some configuration errors on the first run!

**Comment by mdyks01** [comment] 2021-10-18 14:18
I think the update is working, but there seems to be a big new issue.  It looks like all files are being wiped rather than just the modified file that is uploaded.  If you using "ftc_httpd --upload" with just a file (rather than uploading everything), the only file that exists after the upload is the modified file.  Everything else is deleted.

**Comment by mdyks01** [comment] 2021-10-18 14:22
Also, when I just tried to upload all the source again using "ftc_http --upload", I got this error when it got to the one file that was already in OnBotJava:

Pushing org\firstinspires\ftc\teamcode\subsystems\file.java...thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/robot/controller.rs: 97:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by TheLostLambda** [comment] 2021-10-18 14:34
Thanks for all of the help! I have a version that I'll push your way later today! I'll check that it's only deleting the correct files and track down that crash as well.

Quite sorry for all of the continued trouble! I'll have something to you today!

**Comment by TheLostLambda** [comment] 2021-10-18 23:52
@mdyks01 Sorry this has been such a mess! OnBotJava does some magic folder creation on upload according to the `package ...;` line at the beginning of Java files and that's caused a lot of complications when it comes to deleting the right file (the path of the file being uploaded could be totally different from the one already on the robot controller!)

I've solved this by parsing those package lines so I'd love if you could check this out:
https://github.com/TheLostLambda/ftc_http/actions/runs/1356945327

Thank you for all of your continued and dedicated testing!

**Comment by mdyks01** [comment] 2021-10-19 18:11
I hate to say it, but it still doesn't overwrite an existing file.  You're right that the package line can cause a lot of confusion.  However the file I'm testing is just in the root of teamcode and the package line doesn't change its location.  Doing 'ftc_http -h' shows 2.2.0.  Doing 'ftc_http --upload file.java' (from the teamcode directory) uploads the file if it isn't there, but won't update the file if it already exists. I'm reloading OnBotJava to see if the file changes and it doesn't.

**Comment by TheLostLambda** [comment] 2021-10-19 19:17
@mdyks01 would you be able to share in some more detail how you are testing and which files you're trying to upload? Things seem to be working for me, but I'm probably missing a corner case!

**Comment by mdyks01** [comment] 2021-10-19 20:22
I'm not doing anything unusual.  Very straightforward.  I have a file in teamcode called Test.java:
-----------------------------------------------
package org.firstinspires.ftc.teamcode;

public class Test {
    // todo: write your code here
}
-----------------------------------------------

I edit that file by adding a comment locally on my computer (Windows).  Then I use 'ftc_http --upload Test.java' from the teamcode directory on my local computer.  The command runs without error (just like if the Test.java didn't exist in OnBotJava).  I reload OnBotJava and click on Test.java.  The old file is still there, not the modified one.

Really basic.  No edge cases.

I downloaded this file: https://github.com/TheLostLambda/ftc_http/suites/4090402433/artifacts/104206920

ftc_http -h shows "2.2.0"

Here's a transcript of what I did.  teamcode starts out not having Test.java at all:

-------------------------------------------------------------------------------------------------------------
K:\My Drive\src\FreightFrenzy\org\firstinspires\ftc\teamcode>type Test.java
package org.firstinspires.ftc.teamcode;


public class Test {

    // todo: write your code here
}

K:\My Drive\src\FreightFrenzy\org\firstinspires\ftc\teamcode>ftc_http --upload Test.java
Trying host http://192.168.43.1:8080/...online
Pushing Test.java...done

K:\My Drive\src\FreightFrenzy\org\firstinspires\ftc\teamcode>echo // MODIFIED >> Test.java

K:\My Drive\src\FreightFrenzy\org\firstinspires\ftc\teamcode>type Test.java
package org.firstinspires.ftc.teamcode;


public class Test {

    // todo: write your code here
}
// MODIFIED

K:\My Drive\src\FreightFrenzy\org\firstinspires\ftc\teamcode>ftc_http --upload Test.java
Trying host http://192.168.43.1:8080/...online
Pushing Test.java...done

K:\My Drive\src\FreightFrenzy\org\firstinspires\ftc\teamcode>ftc_http -h
ftc_http 2.2.0
Brooks J Rady <b.j.rady@gmail.com>
[...]
-------------------------------------------------------------------------------------------------------------

After running this, Test.java in OnBotJava does not end with "// MODIFIED".

**Comment by TheLostLambda** [comment] 2021-10-19 21:02
Curiously I'm not able to reproduce this problem! Following the same steps that you have provided works for me. Have you refreshed the `OnBotJava` webpage when verifying that the upload worked? The page doesn't automatically update, so if you are using the web UI to check things, you'll need to refresh the page :)

(I'm trying on Windows now just in case it's a platform problem!)

**Comment by TheLostLambda** [comment] 2021-10-19 21:15
Update, it's a bit inconsistent! Now I am seeing the error! I'll keep you updated – thanks again for the infinite patience! 

EDIT: *I* was testing the wrong binary for part of that! Things still seem to be working correctly on 2.2.0!

**Comment by TheLostLambda** [comment] 2021-10-19 21:34
Things working for me / my experience:

https://user-images.githubusercontent.com/6251883/137993924-63b55951-0b59-4340-8ae0-56691e5d828d.mp4

Some things to check?

https://user-images.githubusercontent.com/6251883/137993929-10c28a64-06ab-40e7-ba3a-870d2de4ec26.mp4

**Comment by TheLostLambda** [comment] 2021-10-19 23:54
@mdyks01 It's a Windows specific issue! Rust uses Windows style paths on Windows, but OnBotJava always uses the Unix ones! Should be a simple fix now :)

**Comment by TheLostLambda** [comment] 2021-10-20 00:33
@mdyks01 Sorry for the absolute mess this has been!

Give these a try? They work for me on Windows and Linux :)
https://github.com/TheLostLambda/ftc_http/actions/runs/1361482307

**Comment by mdyks01** [comment] 2021-10-20 01:58
A quick test shows that it works!  Thanks for keeping at it. It's a handy tool that would be missed. I'll test it more soon.

**Comment by TheLostLambda** [comment] 2021-10-20 02:10
Sounds good! I'll do some more testing and improve some error handling before releasing a new version soon!

Thanks for all of your help as well!

**Comment by mdyks01** [comment] 2021-10-21 15:53
I was able to use ftc_http in more of a real world experience recently and it worked well.  Only issue I'm seeing is that when you do a --build with this version it seems to time out after about 15 seconds and put up an error:

Building..............................BUILD TIMEOUT
The build system appears unresponsive. Please restart the robot controller.

However the build does continue and succeeds if viewed through OnBotJava.  The old version seemed to display many more periods while waiting and wait for a long time.  It's not uncommon for our build to take a little over 30 seconds the first time it's run after turning on the robot controller.  Our build times vary from just over 10 seconds to just over 30 seconds.

Thanks for getting this going again.

**Comment by TheLostLambda** [comment] 2021-10-21 15:58
Thanks @mdyks01 ! That's some really good feedback!

The option to set a custom timeout will be available in the version that I release today so it should be user-settable, but I will change the default timeout to 45 seconds if you think that that works? I could also do a full minute (60 seconds) if you think that would be better.

Before there was no timeout at all, so there was no way of informing the user if the build system stopped responding (something that happened often on my phone)!

Thanks again for the dedicated error reporting and testing!

**Comment by mdyks01** [comment] 2021-10-21 16:01
We have a pretty big code base and I've never seen it reach 45 seconds so that seems like a reasonable default.

**Comment by TheLostLambda** [comment] 2021-10-21 16:02
Awesome! I'll make that change now and start working on a release!

**Comment by TheLostLambda** [comment] 2021-10-21 21:04
Things should be polished and published here:
https://github.com/TheLostLambda/ftc_http/releases/tag/v2.2.0

If that continues to work for you (as it does for me on Windows) then we can finally close this issue!

Thank you for your persistence and using `ftc_http`!

**Comment by TheLostLambda** [comment] 2021-10-26 15:37
Hi @mdyks01 ! Closing this now, assuming things are solved for you!

Obviously feel free to reopen if you have any more issues!

Thanks for using `ftc_http`!

**Closed as completed by TheLostLambda** 2021-10-26 15:37 UTC
